version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emailsas-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.rkfwraxddyozjcgssjii:Dandothkar1998@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
      - SECRET_KEY=sb_secret_K6EE_4MGbb_P31K26IAVlQ_h0xJMdrW
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - AWS_ACCESS_KEY_ID=your_aws_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret
      - AWS_REGION=us-east-1
      - SUPABASE_URL=https://rkfwraxddyozjcgssjii.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZndyYXhkZHlvempjZ3NzamlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MjEwNDMsImV4cCI6MjA5MTE5NzA0M30.Dw4oUHwzmgDn-KjXWpzwjWmjj71UhDYZUtQwZMAppaE
      - SUPABASE_JWT_SECRET=sb_secret_K6EE_4MGbb_P31K26IAVlQ_h0xJMdrW
      - EURI_API_KEY=euri-351c19b79882ccf8b485d7ede06003c6991d5d96c022950766d33b43ef6ab4dc
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=manikprabhu0098@gmail.com
      - SMTP_PASSWORD=betxzcqnluezyozt
      - SMTP_USE_TLS=True
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USERNAME=manikprabhu0098@gmail.com
      - IMAP_PASSWORD=betxzcqnluezyozt
      - IMAP_USE_SSL=True
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emailsas-frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
